version: '3.1'

services:
  site:
    build: .
    container_name: hypemap
    ports:
      - "8080:8081"

  pg_db:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1324
      - POSTGRES_DB=hypemap
    volumes:
      - db_pg_dart:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    container_name: pg_db

  adminer:
    image: admin
    restart: always
    ports:
      - "8087:8088"
    container_name: admin

volumes:
  db_pg_dart:
