version: '3.1'

services:
  site:
    build: .
    container_name: bbback
    ports:
      - "8080:8081"

  pg_db:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a0a65e9085b36e6b3f86fe9cf5401f6d03b9880f
      - POSTGRES_DB=dartback
    volumes:
      - db_pg_dart:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    container_name: pg_db

  adminer:
    image: adminer
    restart: always
    ports:
      - "8087:8088"
    container_name: adminer

volumes:
  db_pg_dart:
